# Generated by Django 3.1.7 on 2021-10-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turn',
            old_name='player_reply',
            new_name='player_1_reply',
        ),
        migrations.RenameField(
            model_name='turn',
            old_name='current_player',
            new_name='player_asked',
        ),
        migrations.AddField(
            model_name='turn',
            name='player_2_reply',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='player_3_reply',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='correct_card',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
